<?php

namespace Gajdaw\AngazeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SubjectTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubjectTypeRepository extends EntityRepository
{
}
