<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130510095819 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Journey (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE course ADD courseType_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE course ADD CONSTRAINT FK_11326A8F5DFA93C1 FOREIGN KEY (courseType_id) REFERENCES CourseType (id)");
        $this->addSql("CREATE INDEX IDX_11326A8F5DFA93C1 ON course (courseType_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Journey");
        $this->addSql("ALTER TABLE Course DROP FOREIGN KEY FK_11326A8F5DFA93C1");
        $this->addSql("DROP INDEX IDX_11326A8F5DFA93C1 ON Course");
        $this->addSql("ALTER TABLE Course DROP courseType_id");
    }
}
